### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by hackergrrl** [ipfs/go-libp2p-pubsub#1]
## Roadmap
- [ ] merge into go-ipfs as a CLI command: https://github.com/ipfs/go-ipfs/pull/2599
- [ ] decide on an API: https://github.com/ipfs/notes/issues/118

---

Heya @whyrusleeping! There's a ton of interest in pubsub, but some folks are [unsure](https://github.com/ipfs/notes/issues/108#issuecomment-220630905) of how to approach it. I'm really excited about your implementation here -- what do you think about a roadmap that outlines
1. the current state of this implementation
2. what next steps need to be taken to get this ready for use in go-ipfs proper (if it isn't already) and beyond (integration into libp2p?)

I'm thinking this might help potential contributors (myself included) to get a sense of state and tasks they can pick up, so the community can help out on this. Thanks!

**Comment by whyrusleeping** [comment]
Current state is that the code is functional. I have an open PR that integrates this into go-ipfs as a commad, @haadcode has already provided me some feedback which i need to respond to. More feedback on that end would be very helpful. The real blocker here (aside from time) is deciding on how we want the user API/interface to look/work.

**Comment by hackergrrl** [comment]
1. Functional as in "ready to deploy to prod for everyone to use", or somewhere in between? What tasks need to be done (other than the things you mentioned) to get there?
2. Open go-ipfs pubsub PR: https://github.com/ipfs/go-ipfs/pull/2599
3. For API discussion, we could direct people to issues like https://github.com/ipfs/notes/issues/118 and https://github.com/ipfs/notes/issues/64

**Comment by whyrusleeping** [comment]
Closing this in favor of https://github.com/libp2p/go-floodsub
